categories:
    label: Category
    manage:
        form: $/studioazura/faq/models/category/fields.yaml
        list: $/studioazura/faq/models/category/columns.yaml
    view:
        list: $/studioazura/faq/models/category/columns.yaml
        toolbarButtons: create|delete
        showSearch: true
        defaultSort:
            column: sort_order
            direction: asc

questions:
    label: Question
    manage:
        form: $/studioazura/faq/models/question/fields.yaml
        list: $/studioazura/faq/models/question/columns.yaml
    view:
        list: $/studioazura/faq/models/question/columns.yaml
        toolbarButtons: create|delete
        showSearch: true
        defaultSort:
            column: sort_order
            direction: asc

