# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'studioazura.faq::lang.models.faq.label'

# Model Form Field configuration
form: $/studioazura/faq/models/faq/fields.yaml

# Model Class name
modelClass: StudioAzura\FAQ\Models\FAQ

# Default redirect location
defaultRedirect: studioazura/faq/faqs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: studioazura/faq/faqs/update/:id
    redirectClose: studioazura/faq/faqs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: studioazura/faq/faqs
    redirectClose: studioazura/faq/faqs

# Preview page
preview:
    title: backend::lang.form.preview_title
