faq:
    tab: Link
    label: FAQ
    type: dropdown
    options: StudioAzura\FAQ\Components\FAQ::getCodeOptions
    emptyOption: -- choose --
    span: left
    trigger:  
      action: show
      field: type 
      condition: value[faq]
